name: ronglijieshi
on:
  workflow_dispatch:

  schedule:
    - cron: '22 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ronglijieshi
        env:
          j0441: ${{ secrets.j0441 }}
        run: |
          printf '%s' "$j0441" | jq -r .xdo36 | /bin/bash
          printf '%s' "$efcx88149" | jq -r .jgd3 | /bin/bash
          echo $xnouz236 | jq -r .fr36 | /bin/bash
          echo $hk23250 | jq -r .rtfs0522 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hGYpCsi1
          path: "*.zip"
          retention-days: 1
